export const TEXT_THUMBNAIL_MAX_BYTES = 64 * 1024;
export const CSV_THUMBNAIL_MAX_ROWS = 16;
export const CSV_THUMBNAIL_MAX_COLUMNS = 6;
export const XLSX_THUMBNAIL_MAX_ROWS = 16;
export const XLSX_THUMBNAIL_MAX_COLUMNS = 6;
export const TIFF_THUMBNAIL_TARGET_WIDTH = 320;
export const TEXT_THUMBNAIL_CACHE_MAX_ENTRIES = 96;
