export const CODE_VIEWER_BASE_FONT_PX = 12;
export const CODE_VIEWER_BASE_LINE_PX = 20;
export const CODE_VIEWER_MIN_SCALE = 0.1;
export const CODE_VIEWER_MAX_SCALE = 5;
export const CODE_VIEWER_OVERSCAN_PX = 1000;
export const CODE_VIEWER_BLOCK_PADDING = 8;
export const CODE_VIEWER_INITIAL_VIEWPORT_HEIGHT = 600;
export const CODE_VIEWER_SCROLL_REBASE_CONTAINER_PX = 12_000_000;
export const CODE_VIEWER_SCROLL_REBASE_TRIGGER_PX = 1_000_000;
export const CODE_VIEWER_SCROLL_REBASE_TARGET_PX = 2_000_000;
export const CODE_VIEWER_SCROLL_REBASE_TARGET_BOTTOM_PX =
  CODE_VIEWER_SCROLL_REBASE_CONTAINER_PX - CODE_VIEWER_SCROLL_REBASE_TARGET_PX;
export const CODE_VIEWER_SCROLL_REBASE_THRESHOLD_PX =
  CODE_VIEWER_SCROLL_REBASE_CONTAINER_PX -
  CODE_VIEWER_SCROLL_REBASE_TRIGGER_PX;
export const CODE_VIEWER_LINE_CHECKPOINT_INTERVAL = 4096;

export function clampCodeViewerScale(value: number) {
  return Math.min(
    CODE_VIEWER_MAX_SCALE,
    Math.max(CODE_VIEWER_MIN_SCALE, value),
  );
}
