"use client";

/* eslint-disable no-restricted-syntax -- TODO(no-useEffect): existing direct React effect usage; migrate to useMountEffect or a Rule 1-5 replacement. */

import * as React from "react";

import { MarkdownViewer } from "@/components/ui/markdown-viewer";

const MARKDOWN_VIEWER_DEMO_TEXT = [
  "# Markdown Viewer",
  "",
  "The Markdown Viewer is a continuous Markdown reading surface for very large, mixed-format documents. This demo intentionally packs in prose, tables, code, math, alerts, diagrams, media, raw HTML, component markdown, directive syntax, source highlights, footnotes, and lots of sections so the page behaves like a real long report.",
  "",
  "Actual emoji render inline: 🚀 ✅ 📊 🔒. Gemoji shortcodes render too: :sparkles: :white_check_mark: :warning: :rocket:.",
  "",
  "Inline Markdown includes **bold**, _emphasis_, ~~strikethrough~~, `inline code`, [a local fragment link](#release-readiness-matrix), [an external link](https://retab.com), an autolink https://example.com/reports/alpha, and a footnote reference.[^overview]",
  "",
  "[^overview]: Footnotes stay connected to their references with labelled backrefs.",
  "",
  "> [!IMPORTANT]",
  "> The Markdown Viewer renders the whole document as one continuous, virtualized surface — chunking stays internal, so there are no page frames in the reading experience.",
  "",
  "> [!NOTE]",
  "> GitHub alerts render as labelled regions and remove the marker from visible prose.",
  "",
  "> [!TIP]",
  "> Switch between Rendered and Text mode in the controls to compare the polished view with source-faithful Markdown.",
  "",
  "> [!WARNING]",
  "> The document below includes deliberately long tables, code fences, and repeated chapters to exercise virtualization.",
  "",
  "> [!CAUTION]",
  "> Unsafe raw HTML and unsafe media URLs are intentionally excluded from this sample; policy tests cover those inert paths separately.",
  "",
  'The renderer applies small prose transforms like "smart quotes", arrows ->, and emoji shortcodes :sparkles: without rewriting inline code such as `a -> b`.',
  "",
  "## Current Surface",
  "",
  "- [x] Continuous Markdown rendering",
  "- [x] Pretext-backed layout prediction",
  "- [x] GitHub alert marker normalization",
  "- [x] Tables, lists, quotes, rules, and fenced code blocks",
  "- [x] Mermaid diagrams, math, footnotes, raw HTML policy, and restricted components",
  "- [x] Hostile-block inner virtualization",
  "- [ ] Full production a11y pass across every edge case",
  "",
  "1. Ordered lists preserve start values and nesting.",
  "2. They can contain paragraphs, task lists, and code:",
  "   - [x] Load text resource",
  "   - [x] Build Markdown model",
  "   - [x] Estimate chunk geometry",
  "   - [ ] Measure the visible window",
  "3. The surrounding document stays continuous.",
  "",
  "## Release Readiness Matrix",
  "",
  "| Area | Status | Owner | Risk | Notes |",
  "| :--- | :---: | ---: | ---: | --- |",
  "| Layout | ✅ Ready | Platform | Low | Continuous virtual flow with measured-height correction. |",
  "| Source mode | ✅ Ready | Text | Low | Raw Markdown is virtualized with line numbers. |",
  "| Tables | ✅ Ready | Docs | Medium | Inline Markdown, alignment, scroll, and TSV copy. |",
  "| Code blocks | ✅ Ready | DX | Medium | Source blocks, title/caption metadata, line markers, and copy action. |",
  "| Mermaid | ✅ Ready | Rendering | Medium | Strict security settings and contained failures. |",
  "| Media | ✅ Ready | Policy | Medium | Safe images and videos use the same URL policy. |",
  "| Hostile blocks | ✅ Ready | Perf | Medium | Oversized code, tables, and raw HTML render as bounded copyable source previews. |",
  "",
  "## Code Blocks",
  "",
  '```ts title="markdown-viewer.tsx" caption="A small typed source object passed into the viewer."',
  'import { MarkdownViewer } from "@/components/ui/markdown-viewer"',
  "",
  "export function MarkdownReport({ text }: { text: string }) {",
  "  return (",
  "    <MarkdownViewer",
  "      source={{",
  '        kind: "text",',
  "        text,",
  '        fileName: "report.md",',
  '        mimeType: "text/markdown",',
  "      }}",
  "      highlight={{ start: 42, end: 48 }}",
  "    />",
  "  )",
  "}",
  "```",
  "",
  '```python title="score_pipeline.py" caption="Code blocks should stay readable in long reports."',
  "from dataclasses import dataclass",
  "",
  "@dataclass(frozen=True)",
  "class Score:",
  "    label: str",
  "    value: float",
  "",
  "def summarize(scores: list[Score]) -> dict[str, float]:",
  "    return {score.label: round(score.value, 3) for score in scores}",
  "",
  'print(summarize([Score("precision", 0.982), Score("recall", 0.967)]))',
  "```",
  "",
  '```json title="viewer-resource.json"',
  "{",
  '  "kind": "url",',
  '  "url": "/samples/release-notes.md",',
  '  "fileName": "release-notes.md",',
  '  "mimeType": "text/markdown"',
  "}",
  "```",
  "",
  '```diff title="review.patch"',
  "- render one page at a time",
  "+ render one continuous virtual document",
  "+ measure visible chunks and preserve scroll anchors",
  "```",
  "",
  '```yaml title="frontmatter-example.yaml" caption="Frontmatter-shaped metadata shown as code in this demo."',
  "title: Markdown Viewer Comprehensive Demo",
  "version: 2026.06",
  "owner: Viewer Systems",
  "tags:",
  "  - markdown",
  "  - virtualization",
  "  - diagrams",
  "  - rich-documents",
  "```",
  "",
  "## Diagrams",
  "",
  "```mermaid",
  "flowchart LR",
  "  A[Source text] --> B[Markdown model]",
  "  B --> C[Pretext layout]",
  "  C --> D[Virtual window]",
  "  D --> E[Rendered chunks]",
  "  D --> F[Source mode]",
  "```",
  "",
  "```mermaid",
  "sequenceDiagram",
  "  participant User",
  "  participant Viewer",
  "  participant Model",
  "  User->>Viewer: scroll",
  "  Viewer->>Model: resolve visible chunks",
  "  Model-->>Viewer: chunk frames",
  "  Viewer-->>User: stable rendered window",
  "```",
  "",
  '<Diagram type="mermaid" title="Component diagram" source="graph TD; Source[Source]-->Policy[Policy]; Policy-->Renderer[Renderer]; Renderer-->Document[Document]" />',
  "",
  "## Math",
  "",
  "Inline math renders in prose: $E = mc^2$, $\\alpha + \\beta = \\gamma$, and $P(A\\mid B)=\\frac{P(B\\mid A)P(A)}{P(B)}$.",
  "",
  "$$",
  "\\operatorname{score}(d) = \\sum_{i=1}^{n} w_i x_i - \\lambda \\lVert d \\rVert_2",
  "$$",
  "",
  "## Components And Directives",
  "",
  '<Metric label="Parse accuracy" value="99.2%" />',
  '<Metric label="Mounted chunks" value="small window" />',
  '<Badge label="Stable" tone="success" /> <Badge label="Watch" tone="warning" /> <Badge label="Policy" tone="default" />',
  "",
  '<Callout kind="warning" title="Review generated reports">',
  "",
  "Component Markdown can contain **safe Markdown children**, lists, `inline code`, and links to [local sections](#code-blocks).",
  "",
  "</Callout>",
  "",
  ':::tip{title="Directive callout"}',
  "Directive callouts use the same safe callout surface as component Markdown.",
  ":::",
  "",
  '::metric{label="Directive metric" value="42 ms"}',
  ':badge[Directive badge]{tone="success"}',
  '::diagram{type="mermaid" title="Directive diagram" source="graph LR; A[Directive]-->B[Component]; B-->C[Rendered]"}',
  "",
  '<Accordion title="Expandable audit notes">',
  "",
  "- Accordion content preserves Markdown children.",
  "- It can include `inline code`, **formatting**, and references.[^accordion]",
  "- It should not break surrounding virtual layout.",
  "",
  "</Accordion>",
  "",
  "[^accordion]: This footnote originates inside a component-adjacent part of the sample.",
  "",
  '::::tabs{label="Viewer states"}',
  ':::tab{title="Rendered"}',
  "Rendered mode shows polished Markdown semantics.",
  ":::",
  ':::tab{title="Text"}',
  "Text mode keeps source line numbers and raw Markdown characters.",
  ":::",
  ':::tab{title="Policy"}',
  "Unsafe component props and unsupported component names render inertly.",
  ":::",
  "::::",
  "",
  "## Media",
  "",
  '![Dashboard preview](/samples/attention-page-1.png "Safe PNG image rendered through the image surface")',
  "",
  '::image{src="/samples/attention-page-1.png" alt="Attention sample page" title="PNG image loaded from public samples"}',
  "",
  "## Raw HTML Policy",
  "",
  '<details><summary>Open raw HTML details</summary><p>Safe static HTML like <mark>mark</mark>, <kbd>Cmd</kbd> + <kbd>K</kbd>, H<sub>2</sub>O, x<sup>2</sup>, definition lists, <a href="https://example.com/raw" target="_self" rel="opener">raw external links</a>, and <a href="/docs/components/file-viewer" target="_blank" rel="opener">raw internal links</a> is allowed.</p></details>',
  "",
  "<dl><dt>Continuous surface</dt><dd>No visible page frames or page labels.</dd><dt>Virtualization</dt><dd>Chunking stays internal to scrolling and measurement.</dd></dl>",
  "",
  "<figure><figcaption>Inline figure caption from safe raw HTML.</figcaption></figure>",
  "",
  "## Blockquotes And Rules",
  "",
  "> Markdown should read like a document, not like source code.",
  ">",
  "> Nested prose in blockquotes keeps spacing and wrapping under control.",
  "",
  "---",
  "",
  "## Dense Table",
  "",
  "| # | Scenario | Input | Expected behavior | Verification |",
  "| ---: | --- | --- | --- | --- |",
  ...Array.from({ length: 18 }, (_, index) => {
    const rowNumber = index + 1;
    return `| ${rowNumber} | Scenario ${rowNumber} | Markdown, HTML, math, or component syntax | Render safely without horizontal page growth | Browser smoke and focused tests |`;
  }),
  "",
  "## Hostile Blocks",
  "",
  "Oversized blocks stay inspectable without mounting the full rich subtree. This deliberately large code fence and table should render as bounded source previews with copy actions.",
  "",
  '```ts title="huge-generated.ts"',
  ...Array.from(
    { length: 460 },
    (_, index) => `export const generatedLine${index + 1} = ${index + 1}`,
  ),
  "```",
  "",
  "| Row | A | B | C | D | E | F | G |",
  "| ---: | --- | --- | --- | --- | --- | --- | --- |",
  ...Array.from({ length: 252 }, (_, rowIndex) => {
    const rowNumber = rowIndex + 1;
    return `| ${rowNumber} | alpha-${rowNumber} | beta-${rowNumber} | gamma-${rowNumber} | delta-${rowNumber} | epsilon-${rowNumber} | zeta-${rowNumber} | eta-${rowNumber} |`;
  }),
  "",
  "---",
  "",
  ...Array.from({ length: 36 }, (_, index) => {
    const section = index + 1;
    return [
      `## Long Report Section ${section}`,
      "",
      `This section gives the demo enough length to behave like a multi-page report while staying in one continuous scroll surface. It includes paragraph ${section} with repeated semantic variety, a local anchor target, and enough text for wrapping and measured-height correction.`,
      "",
      `- Section ${section} checklist item A with **bold context** and :sparkles:.`,
      `- Section ${section} checklist item B with \`inline_${section}\` code and a long-token guard: retab_pretext_markdown_viewer_section_${section}_unbroken_identifier_for_wrapping_verification.`,
      `- Section ${section} checklist item C with a nested ordered list:`,
      "  1. Capture scroll anchor.",
      "  2. Recompute layout.",
      "  3. Restore viewport position.",
      "",
      `| Metric | Value |`,
      `| --- | ---: |`,
      `| Section | ${section} |`,
      `| Estimated chunks | ${section * 3} |`,
      `| Mounted window | visible only |`,
      "",
      "> [!NOTE]",
      `> Repeated section ${section} keeps alert rendering common across the long document.`,
    ].join("\n");
  }),
].join("\n");

export function MarkdownViewerDemo() {
  const [isMounted, setIsMounted] = React.useState(false);

  React.useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <div className="h-[620px] min-h-0">
      {isMounted ? (
        <MarkdownViewer
          source={{
            kind: "text",
            text: MARKDOWN_VIEWER_DEMO_TEXT,
            fileName: "pretext-release-notes.md",
            mimeType: "text/markdown",
          }}
          className="h-full"
        />
      ) : null}
    </div>
  );
}
